'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(mode='normal'){
 const listeners={},els={},timers=new Map();let ticks=0,calls=0,resolve,reject,reports=0;
 const el=id=>els[id]||=( {disabled:false,checked:false,textContent:'',addEventListener(t,fn){listeners[id+':'+t]=fn;}} );
 const doc={documentElement:{},getElementById:el,addEventListener(t,fn){listeners[t]=fn;}};
 if(mode!=='unsupported'){doc.fullscreenElement=null;doc.fullscreenEnabled=true;doc.documentElement.requestFullscreen=()=>{calls++;return new Promise((a,b)=>{resolve=a;reject=b;});};doc.exitFullscreen=()=>{calls++;return new Promise((a,b)=>{resolve=a;reject=b;});};}
 const win={addEventListener(t,fn){listeners[t]=fn;}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../fullscreen.js'),'utf8'),{document:doc,window:win,sampleGeometry:r=>({reason:r,screenCss:{width:1280},viewportCss:{innerWidth:doc.fullscreenElement?1280:900},dpr:1.5,visualViewport:{scale:1},estimatedDevicePixels:{screen:{width:1920}}}),report(){reports++;},setTimeout(fn,ms){timers.set(++ticks,{fn,ms});return ticks;},clearTimeout(id){timers.delete(id);},Date,JSON});
 return {doc,win,el,get calls(){return calls;},resolve:()=>resolve(),reject:()=>reject({name:'NotAllowedError',message:'denied'}),emit:t=>listeners[t]({type:t}),park(){el('parked').checked=true;listeners['parked:change']();},flush(ms){for(const [id,t]of [...timers])if(t.ms===ms){timers.delete(id);t.fn();}},result:()=>win.fullscreenReport()};
}
test('parking gates entry, repeated pending clicks make one direct API call',()=>{const s=setup();s.el('fullscreenEnter').onclick();assert.equal(s.calls,0);s.park();s.el('fullscreenEnter').onclick();s.el('fullscreenEnter').onclick();assert.equal(s.calls,1);assert.equal(s.result().attempts[0].outcome,'pending');assert.equal(s.el('fullscreenEnter').disabled,true);});
test('Promise resolution alone never declares success; timeout allows retry',async()=>{const s=setup();s.park();s.el('fullscreenEnter').onclick();s.resolve();await Promise.resolve();assert.equal(s.result().attempts[0].outcome,'pending');s.flush(5000);assert.equal(s.result().attempts[0].outcome,'unconfirmed');assert.equal(s.el('fullscreenEnter').disabled,false);});
test('actual state confirms entry and settled before/after, external exit recorded',()=>{const s=setup();s.park();s.el('fullscreenEnter').onclick();s.doc.fullscreenElement=s.doc.documentElement;s.emit('fullscreenchange');assert.equal(s.result().attempts[0].outcome,'entered');s.flush(300);assert.equal(s.result().attempts[0].before.viewportCss.innerWidth,900);assert.equal(s.result().attempts[0].after.viewportCss.innerWidth,1280);s.doc.fullscreenElement=null;s.emit('fullscreenchange');s.flush(300);assert.equal(s.result().capabilities.active,false);assert.equal(s.result().events.length,2);assert.equal(s.el('fullscreenEnter').disabled,false);});
test('rejection keeps useful name and enables manual retry',async()=>{const s=setup();s.park();s.el('fullscreenEnter').onclick();s.reject();await Promise.resolve();assert.equal(s.result().attempts[0].error.name,'NotAllowedError');assert.equal(s.result().attempts[0].outcome,'failed');assert.equal(s.el('fullscreenEnter').disabled,false);});
test('missing APIs are safe and unsupported buttons remain disabled',()=>{const s=setup('unsupported');s.park();s.el('fullscreenEnter').onclick();assert.equal(s.calls,0);assert.equal(s.el('fullscreenEnter').disabled,true);assert.equal(s.result().capabilities.fullscreenEnabled,null);});
test('manual exit works even after parked checkbox is unchecked',()=>{const s=setup();s.doc.fullscreenElement=s.doc.documentElement;s.emit('fullscreenchange');s.el('fullscreenExit').onclick();assert.equal(s.calls,1);s.doc.fullscreenElement=null;s.emit('fullscreenchange');assert.equal(s.result().attempts[0].outcome,'exited');});
test('fullscreenerror settles failure and records event',()=>{const s=setup();s.park();s.el('fullscreenEnter').onclick();s.emit('fullscreenerror');assert.equal(s.result().attempts[0].error.name,'FullscreenError');assert.equal(s.result().pending,null);});
test('prefixed APIs and events supported',()=>{const s=setup();s.doc.documentElement.webkitRequestFullscreen=s.doc.documentElement.requestFullscreen;delete s.doc.documentElement.requestFullscreen;s.doc.webkitExitFullscreen=s.doc.exitFullscreen;delete s.doc.exitFullscreen;s.doc.webkitFullscreenEnabled=true;delete s.doc.fullscreenEnabled;s.park();s.el('fullscreenEnter').onclick();s.doc.webkitFullscreenElement=s.doc.documentElement;s.emit('webkitfullscreenchange');assert.equal(s.result().attempts[0].outcome,'entered');assert.equal(s.result().capabilities.request,'webkitRequestFullscreen');});
