'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
function target(extra={}){const listeners={};return Object.assign({addEventListener(type,fn){(listeners[type]||=[]).push(fn);},emit(type){for(const fn of listeners[type]||[])fn();}},extra);}
function setup({visual=true}={}){
 const elements=new Map();let copied=null,downloaded=null;
 const document=target({documentElement:{clientWidth:1000,clientHeight:700},fullscreenElement:null,body:{append(){}},getElementById(id){if(!elements.has(id))elements.set(id,target({textContent:'',value:'',focus(){},select(){}}));return elements.get(id);},createElement(){return {click(){},remove(){}};}});
 const window=target({screen:{width:1280,height:800,availWidth:1280,availHeight:760,orientation:target({type:'landscape-primary',angle:0})},innerWidth:1024,innerHeight:720,devicePixelRatio:1.53,isSecureContext:true});
 if(visual)window.visualViewport=target({width:1024,height:720,scale:1,offsetLeft:0,offsetTop:0,pageLeft:0,pageTop:0});
 const navigator={userAgent:'Chrome/120.0',maxTouchPoints:5,clipboard:{async writeText(text){copied=text;}}};
 const context=vm.createContext({window,document,navigator,Map,Date,Number,Blob,URL:{createObjectURL(blob){downloaded=blob;return 'blob:test';},revokeObjectURL(){}},setTimeout(){},clearTimeout(){}});
 vm.runInContext(source,context);
 return {window,document,elements,context,sample:()=>JSON.parse(vm.runInContext('JSON.stringify(sampleGeometry("test"))',context)),report:()=>vm.runInContext('report()',context),copied:()=>copied,downloaded:()=>downloaded};
}
function geometry(text){return JSON.parse(text.split('\n').find(line=>line.startsWith('geometry=')).slice(9));}
test('load samples CSS values, fractional DPR and separated rounded estimates',()=>{const s=setup(),g=s.sample();assert.equal(g.dpr,1.53);assert.deepEqual(g.estimatedDevicePixels.screen,{width:1958,height:1224});assert.deepEqual(g.estimatedDevicePixels.viewport,{width:1567,height:1102});assert.equal(g.screenCss.width,1280);assert.equal(g.viewportCss.clientWidth,1000);assert.match(g.estimatedDevicePixels.method,/not verified native/);assert.ok(!isNaN(Date.parse(g.sampledAt)));assert.equal(s.elements.get('screenDpr').textContent,'1.53');});
test('report and copy resample immediately without waiting for events',async()=>{const s=setup();s.window.innerWidth=900;s.window.devicePixelRatio=2;assert.equal(geometry(s.report()).viewportCss.innerWidth,900);s.window.innerWidth=800;await s.elements.get('copy').onclick();assert.equal(geometry(s.copied()).viewportCss.innerWidth,800);assert.equal(geometry(s.copied()).dpr,2);});
test('TXT download contains fresh geometry JSON and preserves existing reports',async()=>{const s=setup();s.window.innerHeight=600;s.window.audioReport=()=>({status:'untested'});s.elements.get('download').onclick();const text=await s.downloaded().text();assert.equal(geometry(text).viewportCss.innerHeight,600);assert.match(text,/audio=\{"status":"untested"\}/);assert.match(text,/h264: not tested/);assert.match(text,/touch=/);});
test('window and visual viewport events update visible measurements',()=>{const s=setup();s.window.innerWidth=888;s.window.emit('resize');assert.equal(s.elements.get('viewportInner').textContent,'888 × 720');s.window.visualViewport.width=444;s.window.visualViewport.scale=2;s.window.visualViewport.emit('resize');assert.equal(s.elements.get('visualSize').textContent,'444 × 720');assert.equal(s.elements.get('visualScale').textContent,'2');s.window.visualViewport.offsetLeft=12;s.window.visualViewport.emit('scroll');assert.equal(s.elements.get('visualOffsets').textContent,'12 × 0');s.document.fullscreenElement={};s.document.emit('fullscreenchange');assert.equal(s.elements.get('screenFullscreen').textContent,'是');s.window.screen.orientation.angle=90;s.window.screen.orientation.emit('change');assert.match(s.elements.get('screenOrientation').textContent,/90°/);});
test('missing optional APIs yield null, with safe unavailable UI',()=>{const s=setup({visual:false});delete s.window.screen.orientation;delete s.document.fullscreenElement;delete s.window.devicePixelRatio;const g=s.sample();assert.equal(g.visualViewport,null);assert.equal(g.orientation,null);assert.equal(g.fullscreen.active,null);assert.equal(g.dpr,null);assert.equal(g.estimatedDevicePixels.screen.width,null);assert.equal(s.elements.get('visualSize').textContent,'不可用');assert.doesNotThrow(()=>s.report());});
test('no non-finite or invalid dimensions escape, including multiplication overflow',()=>{const s=setup();s.window.innerWidth=Infinity;s.window.innerHeight=NaN;s.window.screen.width=-1;s.window.visualViewport.offsetLeft=Infinity;s.window.visualViewport.scale=0;let g=s.sample();assert.equal(g.viewportCss.innerWidth,null);assert.equal(g.viewportCss.innerHeight,null);assert.equal(g.screenCss.width,null);assert.equal(g.visualViewport.offsetLeft,null);assert.equal(g.visualViewport.scale,null);s.window.innerWidth=Number.MAX_VALUE;s.window.devicePixelRatio=Number.MAX_VALUE;g=s.sample();assert.equal(g.estimatedDevicePixels.viewport.width,null);assert.doesNotMatch(s.report(),/NaN|Infinity/);});
